os: linux
dist: focal

language: scala

scala:
  - 2.13.2

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

services:
  - postgresql

before_script:
  - psql --version
  - psql -U postgres -c "CREATE ROLE saifu_mlm_engin_db_user LOGIN PASSWORD 'password';"
