os: linux
dist: focal
language: scala
scala:
- 2.13.2
jdk:
- openjdk11
services:
- postgresql
addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_script:
- psql --version
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1
- psql -c "CREATE ROLE saifu_mlm_engine_db_user LOGIN PASSWORD 'password';" -U postgres
- psql -c "CREATE DATABASE saifu_mlm_engine_db;" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON DATABASE saifu_mlm_engine_db TO saifu_mlm_engine_db_user;"
  -U postgres
- sbt flyway/flywayMigrate

deploy:
  provider: heroku
  api_key:
    secure: mJX+TR9ukF2geogGP1C6D6fFJ5TwAHV6L+OAjMxsQpyR2o8cXgFdpoh8YJeoNe8ayLcESQoHDF7EB15HFZtwiwVLBaQNzxDKZfdLr8MKxr11ozvgzzJje9oNgqJbvc2F+rvWgtd/SRKkxnCfRlW9ke1sE6TqY1k4935LDi6HfiMUy4etvHgDT314cSDPGKPZ7PibtB8DPvRei+c+iarMsL9OArlgg5tm3Rhi0qv+hUFcY/+a5TPoUsBsEd93mfw/2dXYKaiuvMevXlffXIdG3U17EaPLEDfnmT3Z13t0qXMju4kN93EMgk7jqurCMaBFGKV9yqCci946LGLuzZre4e0rNAD2WlsD89C3Klch1BjPZL2ePStRO7yjtxUwjn5FQ+qgcCs7fGV6DJV5r1/r2u0qCJAWQTVfbEvFGe3/gteAeKTR2qPBkiDeZHRUyNC+yu1f3QoUk7bjDLPdmQCY7xc89pza/e6ZiRE+TjYSzqOxPzkUxzwFFGDNmS7Xe3U8Td8OdD9YavM2JdKF8vcKCHrKQuQT3yB7WEd4FDx5iNwpxfpaEZLtSoZcjS/Qeua1ynJkfPUXqMgd8TZxJx8m+IxEiN1BgFsSFwUm5mmJnlYlQdpP+a8/QbOJlgWnqgwPuOUzbKULRbBoLYu9Xb7tD/mjBaEE3tpBXWeU0DqiJaA=
  app: saifu-mlm-engine-dev
  on:
    repo: JojiKoike/saifu-mlm-engine
    branch: feature/prepare_cicd
  skip_cleanup: false
