od: linux
dist: focal

language: scala

scala:
  - 2.13.2

services:
  - postgresql

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_script:
  - psql --version
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - psql -c "CREATE ROLE saifu_mlm_engine_db_user LOGIN PASSWORD 'password';" -U postgres
