os: linux
dist: focal

language: scala

scala:
  - 2.13.2

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

services:
  - postgresql

script:
  psql --version
