version: "3.8"
services:
  db:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      LANG: ja_JP.UTF-8
      POSTGRES_PASSWORD: password
  adm:
    image: dpage/pgadmin4:latest
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin/storage
    ports:
      - "80:80"
      - "443:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
