TRUNCATE TABLE m_users CASCADE;
TRUNCATE TABLE m_tenants CASCADE;
TRUNCATE TABLE m_roles CASCADE;
TRUNCATE TABLE t_saifu_histories CASCADE;
TRUNCATE TABLE m_saifu CASCADE;
TRUNCATE TABLE m_saifu_sub_categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE m_saifu_main_categories RESTART IDENTITY CASCADE;